UniversityCourseAndResultMangementSystem/Controllers/CourseAssignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Management;
using System.Web.Mvc;
using Newtonsoft.Json.Linq;
using UniversityCourseAndResultMangementSystem.Manager;
using UniversityCourseAndResultMangementSystem.Models;

namespace UniversityCourseAndResultMangementSystem.Controllers
{
    public class CourseAssignController : Controller
    {
       DepartmentManager departmentManager = new DepartmentManager();
       TeacherManager teacherManager = new TeacherManager();
       CourseManager courseManager = new CourseManager();
        [HttpGet]
       public ActionResult SaveCourseAssign()
        {
            ViewBag.DepartmentList = departmentManager.GateAllDepertmentManager();
           // ViewBag.TeacherList = teacherManager.GateAllTeacherManager(); 
            return View();
        }
        [HttpPost]
        public ActionResult SaveCourseAssign(CourseAssignModel courseAssignModel)
        {
            ViewBag.message = courseManager.SaveCourseAssignManager(courseAssignModel); 
            ViewBag.DepartmentList = departmentManager.GateAllDepertmentManager();
            return View(); 
        }
        public JsonResult GetTeacherByDepartmentId(int departmentId)
        {
            var teacher = teacherManager.GateAllTeacherManager();
            var teacherList = teacher.Where(x => x.DepartmentId == departmentId).ToList();
            return Json(teacherList, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCourseByDepartmentId(int departmentId)
        {
            var course = courseManager.GateAllCourseManager();
            var courseList = course.Where(x => x.DepartmentId == departmentId).ToList();
            return Json(courseList, JsonRequestBehavior.AllowGet); 
        }
        public JsonResult CreditTakenByTeacher(int? teacherId)
        {
            CourseAssignModel courseTeacher = teacherManager.GatTeacherCreditManger(teacherId);
            return Json(courseTeacher, JsonRequestBehavior.AllowGet); 
        }
        public JsonResult CreditTakenByCourseId(int? passCourse)
        {
            CourseAssignModel courseCredit = courseManager.GateCourseCredit(passCourse);
            return Json(courseCredit, JsonRequestBehavior.AllowGet); 
        }
        public ActionResult ViewCourseStatic()
        {
            ViewBag.departmentList = departmentManager.GateAllDepertmentManager();
         // ViewBag.courseStatic = courseManager.GatAllViewCourseStaticManager(); 
            return View(); 
        }
        public JsonResult ViewCourseStaticByDepartmentId(int? departmentId)
        {
            var courseStatic = courseManager.GatAllViewCourseStaticManager();
            var getCourseStatic = courseStatic.Where(a => a.DepartmentId == departmentId).ToList();
            return Json(getCourseStatic, JsonRequestBehavior.AllowGet); 
        } 
	}
}

UniversityCourseAndResultMangementSystem/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCourseAndResultMangementSystem.Manager;
using UniversityCourseAndResultMangementSystem.Models;

namespace UniversityCourseAndResultMangementSystem.Controllers
{
    public class CourseController : Controller
    {
        CourseManager courseManager = new CourseManager();
        SemesterManager semesterManager = new SemesterManager();
        DepartmentManager departmentManager = new DepartmentManager();


        public ActionResult SaveCourse()
        {
            ViewBag.message = TempData["Msg"];
            ViewBag.DepartmentList = departmentManager.GateAllDepertmentManager();
            ViewBag.SemesterList = semesterManager.GateAllSemesterManager();
            return View();
        }
        [HttpPost]
        public ActionResult SaveCourse(CourseModel courseModel)
        {
                ViewBag.message = courseManager.SaveCourseManager(courseModel);
                //ViewBag.DepartmentList = departmentManager.GateAllDepertmentGateway();
                //ViewBag.SemesterList = semesterManager.GateAllSemesterManager();
                //return View();
                TempData["Msg"] = ViewBag.message;
                return RedirectToAction("SaveCourse");
        }
	
	}
}

UniversityCourseAndResultMangementSystem/Controllers/DepartmetnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCourseAndResultMangementSystem.Manager;
using UniversityCourseAndResultMangementSystem.Models;

namespace UniversityCourseAndResultMangementSystem.Controllers
{
    public class DepartmetnController : Controller
    {
        DepartmentManager departmentManager = new DepartmentManager();
        [HttpGet]
        public ActionResult SaveDepartment()
        {
            ViewBag.message = TempData["Msg"];
            return View();
        }

        [HttpPost]
        public ActionResult SaveDepartment(DepartmentModel departmentModel)
        {
            ViewBag.message = departmentManager.InsertDepartmentManager(departmentModel);
            TempData["Msg"] = ViewBag.message;
            return RedirectToAction("SaveDepartment");
        }
        public ActionResult ViewAllDepartment()
        {
            List<DepartmentModel> department = departmentManager.GateAllDepertmentManager();
            // ViewBag.ViewDepartment = department;
            return View(department);
        }
    }
}

UniversityCourseAndResultMangementSystem/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCourseAndResultMangementSystem.Manager;
using UniversityCourseAndResultMangementSystem.Models;

namespace UniversityCourseAndResultMangementSystem.Controllers
{
    public class TeacherController : Controller
    {
        TeacherManager teacherManager = new TeacherManager();
        DepartmentManager departmentManager = new DepartmentManager();
        DesignationManager designationManager = new DesignationManager();

        [HttpGet]
        public ActionResult SaveTeacher()
        {
            ViewBag.message = TempData["Msg"]; 
            ViewBag.Designation = designationManager.GateAllDesignationManager();
            ViewBag.Department = departmentManager.GateAllDepertmentManager();
            return View();
        }

        [HttpPost]
        public ActionResult SaveTeacher(TeacherModel teacherModel)
        {
           // ViewBag.Designation = designationManager.GateAllDesignationManager();
            //ViewBag.Department = departmentManager.GateAllDepertmentGateway();
            ViewBag.message = teacherManager.SaveTeacherManager(teacherModel);
            //return View();
                 TempData["Msg"] = ViewBag.message;
                 return RedirectToAction("SaveTeacher");
        }

       
	}
}

UniversityCourseAndResultMangementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("SaveDepartment", "SaveDepartment", "Departmetn")</li>*@
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Dapertment
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Save Department","SaveDepartment","Departmetn")</li>
                            <li>@Html.ActionLink("View All Department", "ViewAllDepartment","Departmetn")</li>
                        </ul>
                    </li>
                    
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Course
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Save Course", "SaveCourse", "Course")</li>
                            @*<li>@Html.ActionLink("View All Department", "ViewAllDepartment", "Departmetn")</li>*@
                        </ul>
                    </li>
                    
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Teacher
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Save Teacher", "SaveTeacher", "Teacher")</li>
                            <li>@Html.ActionLink("Course Assign To Teacher", "SaveCourseAssign", "CourseAssign")</li>
                            <li>@Html.ActionLink("View Course Static", "ViewCourseStatic","CourseAssign")</li>
                        </ul>
                    </li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/bootstrap.js"></script>
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>